CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN_ID VARCHAR(50) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100),
    REGISTRATION_DATE DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS SAFETY_MEASURES (
    MEASURE_ID INT PRIMARY KEY AUTO_INCREMENT,
    RISK_LEVEL VARCHAR(10) NOT NULL,
    RECOMMENDATION_TYPE VARCHAR(50) NOT NULL,
    DETAIL_ADVICE TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS USER_HAZARD_REPORTS (
    REPORT_ID INT PRIMARY KEY AUTO_INCREMENT,
    REPORTER_USER_ID INT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    GU_NAME VARCHAR(20) NOT NULL,
    DETAIL_DESCRIPTION TEXT NOT NULL,
    PHOTO_PATH VARCHAR(255),
    REPORT_DATE DATETIME NOT NULL,
    FOREIGN KEY (REPORTER_USER_ID) REFERENCES USERS(USER_ID)
);
CREATE TABLE IF NOT EXISTS ACCIDENT_HOTSPOTS (
    fid BIGINT PRIMARY KEY,
    legal_dong_code VARCHAR(20),
    spot_code VARCHAR(20),
    city_district_name VARCHAR(50),
    spot_name VARCHAR(255),
    accident_count INT,
    casualty_count INT,
    death_count INT,
    severe_injury_count INT,
    minor_injury_count INT,
    reported_injury_count INT,
    longitude DECIMAL(15, 12),
    latitude DECIMAL(15, 12),
    polygon_geom TEXT
);